In [27]:
import numpy as np
import scipy

Let's try some matrix multiplication

In [28]:
x = np.matrix("4.;5.")
A = np.matrix([[1.,2], [3,4], [5,6]])
A*x

matrix([[14.],
        [32.],
        [50.]])

Find the dot product of A and B

In [29]:
 A = np.array([[1,2],[3,4]])
 b = np.array([10, 20])
 np.dot(A,b)

array([ 50, 110])

Solve Ax=b given A and B

In [30]:
from numpy.linalg import solve
solve(A,b)

array([0., 5.])

Find the eigenvalues and eigenvectors of A

In [31]:
from numpy.linalg import eig
eigen_val, eigen_vec = eig(A)
print(eigen_val)
print(eigen_vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


We want to solve $ \int_{0}^{3} x^4 \,dx = \frac{243}{4}$

In [32]:
from scipy.integrate import quad
quad(lambda x: x**4, 0, 3)

(48.599999999999994, 5.39568389967826e-13)

Compute the determinant

In [33]:
x = np.random.rand(4,4)
np.linalg.det(x)

0.029675718387822306

Compute the projection of a onto b

In [34]:
a = np.array([4,5,6])
b = np.array([7,8,9])
proj_b_a = np.inner(a,b) / np.inner(b,b) * b
proj_b_a

array([4.40206186, 5.03092784, 5.65979381])

Show LU decomposition

In [35]:
a = np.random.randn(3,4)
p,l,u = scipy.linalg.lu(a)
print(p)
print(l)
print(u)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [-0.21880936  1.          0.        ]
 [-0.26295089  0.83827213  1.        ]]
[[-2.81160152  0.02814613 -1.50175795 -1.10912189]
 [ 0.         -1.05953994  0.81849686 -0.7242701 ]
 [ 0.          0.         -1.44728658  1.40022812]]


Show QR decomposition

In [36]:
a = np.random.randn(3,4)
q,r = np.linalg.qr(a)
print(q)
print(r)

[[-0.71417816  0.18198865  0.67589178]
 [-0.23632971 -0.97160013  0.01189344]
 [ 0.65886101 -0.15123927  0.73690492]]
[[ 3.3224333   0.78695638  0.51553929  0.1035281 ]
 [ 0.         -0.2330004  -1.80804112  0.5542906 ]
 [ 0.          0.          1.83224094  0.66898584]]
